sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1776463307
  alioss:
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: hrt-sky
